### ISSUE TITLE
Why force user-select: none?

### ISSUE THREAD

**Issue by chentsulin** [chibicode/react-json-tree#10]
I sometimes want to select part of store's state or actions and copy them paste into other place (maybe for search), but select and copy is disabled by `user-select: none`. Are there any concerns about this?

**Comment by chibicode** [comment]
`user-select` was added on this commit before porting to this repo:
https://github.com/gaearon/redux-devtools/commit/45086e246c4ff3ef4bf9a54b030b55f520a14918

I think the only concern was that selecting can trigger open/close event:

![](http://cl.ly/image/371x2T1T1R2n/Screen%20Recording%202015-10-07%20at%2002.52%20PM.gif)

So I disabled `user-select` for leave nodes (bool, date, string, number, and null nodes) b/c there shouldn't be any issue there: e20b631

If someone thinks it should be disabled for everything (including array, object, etc) nodes then I'll just remove all the references to `user-select`.

Further Reading: "Is “user-select: none” bad UX?"
http://ux.stackexchange.com/questions/83184/is-user-select-none-bad-ux

**Comment by chentsulin** [comment]
Thanks for your explanation!
