### ISSUE TITLE
Edit, Add, Delete event

### ISSUE THREAD

**Issue by liangzhijian0** [chibicode/react-json-tree#120]
How to acheive(edit, add, delete) event? I didn't find that in the introduction. And any solution to control some fields that are editable, some fields that are read-only?

**Comment by alexkuz** [comment]
If you need it to be editable, you'll have to implement it by yourself by defining custom `valueRenderer` component.

This package moved to https://github.com/reduxjs/redux-devtools, please ask there if you have further questions.
