### ISSUE TITLE
Every property is Interpreted as String

### ISSUE THREAD

**Issue by duncanfinney** [chibicode/react-json-tree#19]
There seems to have been a regression somewhere between 0.3.0 and 0.4.0. 

In 0.4.0, every property on the object is displayed as a string. 

Very cool project by the way. Exactly what I needed for a chrome extension I'm making.

**Comment by markerikson** [comment]
Appears to have happened in the first "cleanup" commit, 5e516dcd8cf1017970e96322f0607a93db98a5c6 .  Looks like JSONStringNode was renamed to JSONValueNode, and in the process the quotation marks for the value rendering were left in.  Would be nice if that was fixed up.

**Comment by chibicode** [comment]
Thanks for reporting, @bvaughn let me know if you think there's a good way of fixing this, otherwise I can tackle

**Comment by bvaughn** [comment]
My apologies if I caused a regression. I'll try to take a look within the next day or two.

**Comment by bvaughn** [comment]
Fix is available as PR #25

**Comment by duncanfinney** [comment]
Thanks @bvaughn!

**Comment by markerikson** [comment]
Does this fix the syntax highlighting changes as well?  I definitely liked seeing numbers and booleans displayed as a different color.

**Comment by bvaughn** [comment]
Actually, no. I didn't fix the theme color regression with that commit. Sorry! Follow up coming on its way.

**Comment by bvaughn** [comment]
@markerikson thanks for pointing out that issue as well. :)

PR #25 has been updated with that fix:
<img width="302" alt="screen shot 2016-01-12 at 8 36 52 am" src="https://cloud.githubusercontent.com/assets/29597/12269763/d8e1c456-b907-11e5-91fd-9f237ddc05b8.png">

**Comment by markerikson** [comment]
Yay, pretty colors!

Thanks for the fixes.  Much appreciated.

**Comment by bvaughn** [comment]
No problem. My bad for not noticing that regression. :)
This project could use tests. Maybe I'll take the time to write a few soon.

**Comment by chibicode** [comment]
@bvaughn thanks a lot!
