### ISSUE TITLE
Missing changelog for last few releases

### ISSUE THREAD

**Issue by gaearon** [chibicode/react-json-tree#27]
I wanted to update https://github.com/gaearon/redux-devtools-log-monitor to use 0.5.0 but couldn't find the release notes for 0.4.x and 0.5.x. I'm especially interested in breaking changes (as I presume there are some because minor bumped while still on 0.x—were there any?)

**Comment by chibicode** [comment]
Hi @gaearon, sorry about that, I just added them: https://github.com/chibicode/react-json-tree/releases - there shouldn't be any breaking changes other than that Babel is now 6.x.
