### ISSUE TITLE
react 0.13 peer dependency fails

### ISSUE THREAD

**Issue by acthp** [chibicode/react-json-tree#28]
With react 0.13.3, this fails with the errors, below. Upgrading to 0.14 latest, it works.  I see a previous commit to allow earlier 0.13 versions, so not sure why this isn't working. Is there anything special required to use this with react 0.13? I'm rendering like so:

```javascript
    <JSONTree data={{foo:'bar'}}/>
````

and getting these errors with react 0.13.3. No errors with 0.14

    Component(...): No `render` method found on the returned component instance: you may have forgotten to define `render` in your component or you may have accidentally tried to render an element whose type is a function that isn't a React component.

    Warning: Don't set the props property of the React element. Instead, specify the correct value when initially creating the element.

    Uncaught TypeError: Can't add property context, object is not extensible

**Comment by acthp** [comment]
0.3.0 appears to be the last tagged version that works with react 0.13 versions.

**Comment by chibicode** [comment]
@acthp hmm yeah sorry about this. I updated peer dependency to 0.14. We couldn't figure out what went wrong when we merged this particular PR - see the comment:
https://github.com/chibicode/react-json-tree/pull/18#issuecomment-168127846
