### ISSUE TITLE
Reference to Symbol breaks IE11

### ISSUE THREAD

**Issue by insin** [chibicode/react-json-tree#3]
After starting to use redux-devtools, I noticed my app was broken in IE11, caused by the unguarded `typeof obj[Symbol.iterator] === 'function'` check in `obj-type.js`

Guarding the check with `typeof Symbol !== 'undefined'` would make for a quick fix.

Edit: I've just spotted that PR #2 is intended to fix this.

**Comment by janusch** [comment]
I just ran into the same issue, would be great to get a fix in for this. Without a patch the redux-devtools are unusable in IE.

Thanks!

**Comment by chibicode** [comment]
@insin @janusch sorry for the delay. I just merged #2 and pushed to npm. Could you take a look?

**Comment by chibicode** [comment]
Closing this since I haven't heard back for a month.

**Comment by ZxMYS** [comment]
Hi @chibicode this bug appeared in 0.5.2. It seems like 0.4.0 was good.

**Comment by ZxMYS** [comment]
I believe it's caused by your recent upgrade to Babel 6, and you might need to add babel-plugin-transform-runtime to your .babelrc.

**Comment by chibicode** [comment]
@ZxMYS I just pushed 0.5.3 w/ `babel-plugin-transform-runtime` - could you try that?

**Comment by ZxMYS** [comment]
Yes now it works again. Thanks!
