### ISSUE TITLE
Dates aren't displayed

### ISSUE THREAD

**Issue by insin** [chibicode/react-json-tree#4]
There's no `JSONDateNode` to display `Date` values.

This would make an excellent [First Timers Only](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) Pull Request :octocat:

**Comment by chibicode** [comment]
Totally agree :) :octocat:

**Comment by insin** [comment]
- [ ] Add a new `else if` branch to [`grab-node.js`](https://github.com/chibicode/react-json-tree/blob/master/src/grab-node.js) for `nodeType === 'Date'`
- [ ] Create a new `JSONDateNode.js` module in `src/` based on one of the existing components. e.g. copy the contents of [`JSONStringNode.js`](https://github.com/chibicode/react-json-tree/blob/master/src/JSONStringNode.js) and rename the component to `JSONDateNode`
- [ ] Add a property to the `data` object rendered in the example [`App.js`](https://github.com/chibicode/react-json-tree/blob/master/examples/src/App.js)
- [ ] [Run the example](https://github.com/chibicode/react-json-tree/tree/master/examples#usage) to check the date displays and looks ok
- [ ] Decide/discuss how the date should be displayed - e.g. is the default String representation ok, or should the component call [`.toIsoString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) or something else when rendering?

**Comment by Charlotteis** [comment]
Thank you for this great issue, i'll be posting it at 4PM today (GMT Timezone)! :tada:

**Comment by chibicode** [comment]
@Charlotteis I think @liamkennedy89's got here first...
