### ISSUE TITLE
JSONTree expands when loaded from localhost, not from external IP address

### ISSUE THREAD

**Issue by richb-hanover** [chibicode/react-json-tree#40]
I'm using react-json-tree 0.6.1 with node 5.3.0, npm 3.3.12 on OSX 10.10.5 and Chrome (recent).

The site works perfectly if I access it from localhost:3000. Going to my computer's external address (say, 192.168.254.13:3000) the app works fine except that react-json-tree items do not expand (!) Clicking the twisty triangle does not change the appearance - it stays collapsed.

I confess I didn't read much of the documentation - I just slapped the `<JSONTree... />` component in place, and it worked right away.

Any ideas how to troubleshoot this? Thanks.

**Comment by richb-hanover** [comment]
Update: 

- Works with localhost on Chrome 50.0.2661.49 beta (64-bit), doesn't work on external IP address
- Does *not* work on either localhost or external IP with Firefox 45.0.1

**Comment by richb-hanover** [comment]
*Update:* Never mind. An update of many things in my package.json (including to react-json-tree@0.6.3) makes things work whether to localhost or an external IP address. I don't have a specific fix that I can identify, but it's fine now (which is what I would have expected all along...)

**Comment by richb-hanover** [comment]
Nope. I am wrong in the previous symptom description... I am using a slightly complicated npm/hot loading/etc. setup (with which I am not completely familiar). But I have learned this: the bad behavior is dependent on the *port* I connect to, not the hostaddress. Specifically:

either-localhost-or-computers-external-ipaddress:3001 - react-json-tree works as expected
either-localhost-or-computers-external-ipaddress:3000 - items don't expand (the original complaint)

I know this sounds loony: but can anyone guess why connecting to a different port would make a difference? (Any guesses? Any thoughts of avenues to investigate?) Thanks again.

**Comment by alexkuz** [comment]
That does sound weird. To clarify - are you trying it with example project? Did you try to trace what happens in `onClick` handler? (one thing I can think of - there are two handlers, so they could conflict somehow, but it's hard to blame ports for that, obviously).

**Comment by richb-hanover** [comment]
No, this occurs in my own project, which has some fancy proxying going on with both ports 3000 & 3001 (there are a lot of actors involved: webpack hot reloading, webstorm, ....) I was *not* able to reproduce in the tests/example project, so I don't think it's anything related to react-json-tree itself. I was just hoping to  spark a troubleshooting thought from someone here.

I think react-json-tree is off the hook, and that I need to investigate my build system further. You all can take the rest of the day off :-)

**Comment by alexkuz** [comment]
Ok, got it :)
